version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-net

  react-app:
    build:
      context: ./devops-build
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - devops-net

volumes:
  jenkins_home:

networks:
  devops-net:
    driver: bridge
